In [2]:
import numpy as np

import pandas as pd
from pandas import Series,DataFrame

# Concatenation in Numpy:

In [3]:
arr1 = np.arange(9).reshape(3,3)

arr1 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Concatenation in Pandas with Series:

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>T</th>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>U</th>
      <td>1.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>V</th>
      <td>2.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>X</th>
      <td>NaN</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>Y</th>
      <td>NaN</td>
      <td>4.0</td>
    </tr>
  </tbody>
</table>
</div>

In [12]:
# Adding markers/keys to the concat() function to help identify matrices used
# This in other words, creates an index hierarchy
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

# Concatenation in Pandas with DataFrames:

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2.079637</td>
      <td>2.206798</td>
      <td>0.615580</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-1.541504</td>
      <td>0.527272</td>
      <td>0.580309</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.231535</td>
      <td>0.454504</td>
      <td>0.183334</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.203756</td>
      <td>-0.372197</td>
      <td>0.194995</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
dframe2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Y</th>
      <th>Q</th>
      <th>X</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-0.390173</td>
      <td>-1.773354</td>
      <td>1.278931</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-0.393858</td>
      <td>-1.186386</td>
      <td>1.264979</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1.344144</td>
      <td>-0.443264</td>
      <td>0.296437</td>
    </tr>
  </tbody>
</table>
</div>

In [16]:
# notice how the index # for each dataframe was kept when using the concat() function
pd.concat([dframe1,dframe2])

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Q</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>NaN</td>
      <td>2.079637</td>
      <td>2.206798</td>
      <td>0.615580</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NaN</td>
      <td>-1.541504</td>
      <td>0.527272</td>
      <td>0.580309</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NaN</td>
      <td>0.231535</td>
      <td>0.454504</td>
      <td>0.183334</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NaN</td>
      <td>1.203756</td>
      <td>-0.372197</td>
      <td>0.194995</td>
    </tr>
    <tr>
      <th>0</th>
      <td>-1.773354</td>
      <td>1.278931</td>
      <td>-0.390173</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-1.186386</td>
      <td>1.264979</td>
      <td>-0.393858</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-0.443264</td>
      <td>0.296437</td>
      <td>1.344144</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

In [17]:
# Syntax to ignore the default index values of the resulting dataframe
pd.concat([dframe1,dframe2],ignore_index=True)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Q</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>NaN</td>
      <td>2.079637</td>
      <td>2.206798</td>
      <td>0.615580</td>
    </tr>
    <tr>
      <th>1</th>
      <td>NaN</td>
      <td>-1.541504</td>
      <td>0.527272</td>
      <td>0.580309</td>
    </tr>
    <tr>
      <th>2</th>
      <td>NaN</td>
      <td>0.231535</td>
      <td>0.454504</td>
      <td>0.183334</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NaN</td>
      <td>1.203756</td>
      <td>-0.372197</td>
      <td>0.194995</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-1.773354</td>
      <td>1.278931</td>
      <td>-0.390173</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-1.186386</td>
      <td>1.264979</td>
      <td>-0.393858</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-0.443264</td>
      <td>0.296437</td>
      <td>1.344144</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
</div>

In [18]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'