In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

arr

array([0, 1, 2, 3, 4])

- if you want to save your code, use the following syntax:

In [3]:
np.save('myarray',arr)

In [4]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.load('myarray.npy')   # syntax to call your saved array 'myarray' and the numpy extension which is '.npy' 

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarray.npy')

arr1

array([0, 1, 2, 3, 4])

In [8]:
arr2 = arr

arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez('ziparray.npz',x=arr1,y=arr2)

- code above is the method used to save multile arrays in a zip file. 
- Syntax:  'np.savez(z- for zipfile)('zip_nameoffile_.npz')(npz is the zip file extension save 
  method in numpy

- syntax to load multiple arrays is the code below:

In [10]:
archive_array = np.load('ziparray.npz')

In [11]:
archive_array['x']    # calling the first array in ziparray, arr1, which is now saved as a single variable, 'x'

array([0, 1, 2, 3, 4])

In [12]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Syntax to save and load textfiles in case you dont want to save as zip.

In [13]:
arr = np.array([[1,2,3],[4,5,6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

# syntax to save file as a 'textfile'; 'np.method=[savetxt]('_filename_.txt',_arrayname_,delimiter='what separates
# the values within the file/usually a symbol(',:_ etc))

In [19]:
arr = np.loadtxt('mytextarray.txt', delimiter=',')  # syntax to load a 'txt' file

In [17]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])