In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- Universal functions are basic functions that you can apply to every value in an array

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

A

array([ 0.29899359,  0.00832516,  1.14041709,  1.01498018, -1.55556363,
       -0.1714939 , -0.31775253, -0.99167625,  2.2028655 ,  0.12530315])

In [9]:
B = np.random.randn(10)

B 

array([ 0.28497827, -0.13902298,  0.24654235, -0.89709916,  1.02661761,
       -1.00871467,  1.20693806,  2.14023055, -0.23578478, -1.13279979])

In [11]:
# Binary Functions
np.add(A,B)  #  this will add the 1st value of A to the 1st value of B

array([ 0.58397186, -0.13069782,  1.38695944,  0.11788102, -0.52894602,
       -1.18020857,  0.88918553,  1.1485543 ,  1.96708072, -1.00749664])

In [14]:
np.maximum(A,B)  # This syntax will find the maximum value between the specified arrays; 
# compares the value at each index and returns the function call

array([ 0.29899359,  0.00832516,  1.14041709,  1.01498018,  1.02661761,
       -0.1714939 ,  1.20693806,  2.14023055,  2.2028655 ,  0.12530315])