In [3]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

syntax to make an array and store it in a variable, my_list1. 

In [5]:
my_array1 = np.array(my_list1)

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [8]:
my_lists = [my_list1,my_list2]

syntax to create a multi-dimensional array using both created arrays, and storing them in variable, my_lists. 
you can do this by passing each array(stored in a variable) as a parameter to the multi-dimensional array varialbe.

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int64')

syntax to check the data type of a particular array

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
my_zeros_array = np.zeros(5)

In [19]:
my_zeros_array.dtype

dtype('float64')

In [21]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

above syntax used to create an identity matrix

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

syntax to create a range of numbers, starting at zero.

In [29]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

syntax above is used to create a range from 5 to 50, skipping every 2nd number.  the parameters are defined by (start, stop, and step size) 